CREATE TABLE IF NOT EXISTS expense_budget (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise                INTEGER         NOT NULL,
    superior_organ_code     BIGINT          NOT NULL,
    superior_organ_name     VARCHAR(255),
    subordinate_agency_code BIGINT          NOT NULL,
    subordinate_agency_name VARCHAR(255),
    budgetary_unit_code     BIGINT          NOT NULL,
    budgetary_unit_name     VARCHAR(255),
    function_code           BIGINT          NOT NULL,
    function_name           VARCHAR(255),
    subfunction_code        BIGINT          NOT NULL,
    subfunction_name        VARCHAR(255),
    budget_program_code     VARCHAR(20)     NOT NULL,
    budget_program_name     VARCHAR(255),
    action_code             VARCHAR(20)     NOT NULL,
    action_name             VARCHAR(500),
    economic_category_code  BIGINT          NOT NULL,
    economic_category       VARCHAR(255),
    expense_group_code      SMALLINT        NOT NULL,
    expense_group_name      VARCHAR(255),
    expense_element_code    BIGINT          NOT NULL,
    expense_element_name    VARCHAR(255),
    initial_budget          NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    updated_budget          NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    committed_budget        NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    executed_budget         NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    percent_executed_budget NUMERIC(7, 4)   NOT NULL DEFAULT 0,
    inserted_at             TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP       NOT NULL DEFAULT NOW(),

    UNIQUE (
        exercise,
        subordinate_agency_code,
        budgetary_unit_code,
        function_code,
        subfunction_code,
        budget_program_code,
        action_code,
        economic_category_code,
        expense_group_code,
        expense_element_code
    )
);

CREATE INDEX idx_expense_budget_exercise           ON expense_budget(exercise);
CREATE INDEX idx_expense_budget_subordinate_agency ON expense_budget(subordinate_agency_code);
CREATE INDEX idx_expense_budget_action_code        ON expense_budget(action_code);
